root: .# Theme Check Configurationexclude:



exclude:root: .  - "node_modules/**"

  - node_modules/

  - .git/  - "dist/**"

  - dist/

  - build/exclude:  - "build/**"

  - assets/vendor*.css

  - assets/vendor*.js  - node_modules/  - ".github/**"

  - snippets/shogun-*.liquid

  - .git/  - "assets/**/*.min.css"

ImgLazyLoading:

  enabled: true  - dist/  - "assets/**/*.min.js"

  severity: suggestion

  - build/  - "assets/**/vendor-**/*"

ImgWidthAndHeight:

  enabled: true    - assets/vendor*.css  - "assets/vendor-*.css"

  severity: suggestion

  - assets/vendor*.js  - "assets/vendor-*.js"

RemoteAsset:

  enabled: true  - snippets/shogun-*.liquid  - "snippets/**/shogun-*.liquid"

  severity: suggestion



DeprecatedFilter:

  enabled: trueImgLazyLoading:checks:

  severity: error

  enabled: true  SpaceInsideBraces:

TranslationKeyExists:

  enabled: true  severity: suggestion    enabled: false

  severity: error

  TemplateLength:

SpaceInsideBraces:

  enabled: falseImgWidthAndHeight:    enabled: true



TemplateLength:  enabled: true      severity: suggestion

  enabled: true

  severity: suggestion  severity: suggestion    max_length: 1200

  max_length: 1200

  UnusedAssign:

UnusedAssign:

  severity: suggestionRemoteAsset:    severity: suggestion



ContentForHeaderModification:  enabled: true  UnusedSnippet:

  enabled: false
  severity: suggestion    severity: suggestion

  ContentForHeaderModification:

DeprecateLazysizes:    enabled: false

  enabled: true  ImgWidthAndHeight:

  severity: suggestion    severity: suggestion

  ImgLazyLoading:

DeprecatedFilter:    severity: suggestion

  enabled: true  RemoteAsset:

  severity: error    severity: suggestion

  DeprecatedFilter:

MatchingTranslations:    severity: suggestion

  enabled: true  TranslationKeyExists:

  severity: suggestion    enabled: true

    severity: error

TranslationKeyExists:  MatchingTranslations:

  enabled: true    severity: suggestion

  severity: error  SchemaJsonFormat:

    severity: suggestion

SpaceInsideBraces:

  enabled: false# Exclusions ciblées (au lieu d'un exclude_patterns global)

ImgWidthAndHeight:

TemplateLength:  exclude_patterns:

  enabled: true    - "assets/**/*.min.css"

  severity: suggestion    - "assets/**/*.min.js"

  max_length: 1200

ImgLazyLoading:

UnusedAssign:  exclude_patterns:

  severity: suggestion    - "assets/**/*.min.css"

    - "assets/**/*.min.js"

ContentForHeaderModification:

  enabled: falseRemoteAsset:
  exclude_patterns:
    - "assets/vendor-*.css"
    - "assets/vendor-*.js"
    - "assets/**/vendor-**/*"
