name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
<<<<<<< HEAD
          ruby-version: 3.3
          bundler-cache: true
      - run: gem install theme-check --no-doc
      - run: theme-check --fail-level=error
=======
          ruby-version: '3.2'
      - name: Install theme-check
        run: gem install theme-check
      - name: Run theme-check (fail on errors)
        run: theme-check --fail-level error

  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint GitHub workflows
        uses: rhysd/actionlint@v1
>>>>>>> 5cf52ad (ci: add real checks (theme-check, actionlint, basic-build))

  basic-build:
    name: Basic Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci || npm i --no-audit --no-fund
      - name: Build (if script exists)
        run: |
          if npm run | grep -qE '^  build'; then
            npm run build
          else
            echo "No build script; skipping."
          fi

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci || npm i --no-audit --no-fund
      - name: Run ESLint (optional fallback)
        run: |
          if npm run | grep -qE '^  lint:js'; then
            npm run lint:js
          elif npx eslint --version >/dev/null 2>&1; then
            npx eslint --max-warnings=0 --ext .js,.ts,.tsx assets scripts src || true
          else
            echo "ESLint not configured; skipping."
          fi

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci || npm i --no-audit --no-fund
      - run: npm run lint:css
