name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  theme-check:
    name: theme-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install theme-check
        run: gem install theme-check
      - name: Run theme-check (fail on errors)
        run: theme-check --fail-level error

  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint GitHub workflows
        uses: rhysd/actionlint@v1

  basic-build:
    name: basic-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify theme structure exists
        run: |
          test -d sections || echo "no sections dir (ok for minimal theme)"
          echo "OK"
