name: PR CI

on:
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch: {}

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Ruby + theme-check
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: false
      - name: Run theme-check
        run: |
          bash scripts/theme_check.sh

  basic-build:
    name: Basic Build Sanity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps (prod only)
        run: npm ci --omit=dev || npm install --omit=dev
      - name: List key files
        run: |
          ls -1 locales | head -n 10
          echo '---'
          node -v
      - name: Lint placeholder (extend later)
        run: echo "No JS lint step configured yet"

  summary:
    name: Summary Gate
    runs-on: ubuntu-latest
    needs: [theme-check, basic-build]
    steps:
      - name: Report
        run: echo "All required jobs passed."