name: Secret Scan

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Gitleaks to scan for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
