name: Generate Sitemap

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate sitemap
        run: |
          ./generate-sitemap.sh
      - name: Commit and push sitemap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Automated sitemap update [skip ci]" || echo "No changes to commit"
          git push
